services:
  python-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    env_file: "./src/.env"
    volumes:
      - ${BACKUP_PATH}:${MOUNT_PATH}

  python-analytics:
    build:
      context: .
      dockerfile: Dockerfile.analysis
    env_file: "./src/.env"
    ports:
      - "8000:8000"
    volumes:
      - ${BACKUP_PATH}:${MOUNT_PATH}