class VariableTypeEnum:
    ALLOWED_USERS = "allowed_users"
    BACKUPED_CATEGORIES = "backuped_categories"
    BACKUPED_CHANNELS = "backuped_channels"
    INCREASE_START_DATE_AFTER_BACKUP = "increase_start_date_after_backup"
    START_DATE = "start_date"
    TIMEZONE = "timezone"
    BACKUP_PATH = "backup_path"
    CHANNEL_NAMES = "channel_names"
    USER_NICKNAMES = "user_nicknames"